### ISSUE TITLE
typo and suggestion one more include file type, utf8 encoding default

### ISSUE THREAD

**Issue by mrfragger** [MatteoGuadrini/mkpl#9]
```
7. Create playlist with music and video files if files is greater then 10MB

7. Create playlist with music and video files if files are greater than 10MB
```

still haven't tried it out yet but will soon.  Just by looking at the examples I'm not clear the difference between 

`-f | --format | Select only a file format | Format of file. ex. mp3`

`-i | --include | Include other file format | Format of file. ex. mp3`

so is -i like appending -i mp3 opus (so adding multiple files)   
-f is saying choose mp3 and exclude all others?

`mkpl -d "new_collection" -r "my music.m3u" -g "UTF-8"`
Also is there a reason why utf-8 encoding isn't the default? I remember pysubs2 eventually made it the default about a year or so ago.

the sort and regex features are awesome..very powerful stuff...

**Comment by MatteoGuadrini** [comment]
Hi @mrfragger,
thanks for the correction in example 7.

Unlike other tools I've written, I've never fully documented this one, because I always thought it was clear how to use it. But I understand that in fact I have described the args sufficiently and not exhaustively.

Anyway, to explain better:
* `-f` or `--format`, as the help says, _"Select only a file format (default: None)"_, that is, select a format from the predefined ones: `mp1,wav,xvid,vob,flac, 3gp,webm,wma,flv,mpeg,m4a,mp2,ape,opus,aiff,f4a,alac,mp3,mpg,wmv,ogg,asf,aac,m4v,mov,mp4,divx,avi`
* `-i` or `--include`, as the help says, _"Include other file format (default: None)"_, i.e. it does not add any other formats other than those listed above. If you use it like this: `mkpl -i mpeg6` or `mkpl -i .mpeg6`, also add the _mpeg6_ format to the format list.

The file encoding is by default in **UTF-8** (see writing the file): https://github.com/MatteoGuadrini/mkpl/blob/main/mkpl.py#L399

The `-g` or `--encoding` option concerns the encoding not of the file format, but of the M3U extension which tells the media player that reads the M3U file how it should read and parse the lines contained in it .

I hope I have clarified all your questions. If I may advise you, the tool's help (`mkpl -h`) is much more comprehensive than the README.
